[package]
name = "superlight-ipc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
superlight-core = { path = "../superlight-core" }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
getrandom = "0.3"
interprocess = "=2.4.2"
