[package]
name = "superlight-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints.clippy]
collapsible_if = "allow"

[[bin]]
name = "superlight-ui"
path = "src/main.rs"

[dependencies]
superlight-core = { path = "../superlight-core" }
superlight-ipc = { path = "../superlight-ipc" }
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
eframe = { version = "=0.36.2", default-features = false, features = ["default_fonts", "glow"] }
image = { version = "0.25", default-features = false, features = ["png"] }
